acmcsufoss/1st

index.html

Updated index.html with my name and Github account! :D

This is your change

---

collaborators/jowen-ster.md

PLEASE MERGE OMG PLEASEEEEEEEEE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE

---

collaborators/big-o.md

This is absolutely necessary, ngl...

Necessary change!!!!!!

---

collaborators/johncmanuel.md
index.html

added johncmanuel.md

---

collaborators/SepehrKermanshah.md
index.html

@SepehrDebah 

---

collaborators/contributor.md

Add TheFishEy

---

collaborators/keillor.md
index.html

*wheeeeeee*
added md file with Keillor GitHub link attached.

added me GitHub on a little md file

---

collaborators/santosh.md
index.html

Hello this is Santosh. This is my first contribution to open-source

added my profile

---

src/contributors/fa24/26samaahmed.md

Edit my message

---

src/contributors/fa24/karnikaavelumani.md

Create `karnikaavelumani.md` file

---

src/contributors/fa24/abledaniel.md

Add Abel markdown

---

src/contributors/fa24/ryan-avancena.md

yoooooooooooo, added markdown file and description

add ryan markdown

---

src/contributors/fa24/KQPH.md

Added markdown file for Kyle Ho

Added KQPH.md

---

src/contributors/fa24/bebopkenny.md

add kenny markdown

---

src/contributors/fa24/rhellwege.md

Add Ryan Hellwege markdown

---

src/contributors/fa24/mary23386.md

Add Mariia Grushina

---

src/contributors/fa24/loricha.md

Added my markdown file and some description.

Add Lori Cha markdown

---

src/contributors/fa24/thecodeofdaniel.md

Add thecodeofdaniel markdown

---

src/contributors/fa24/ddusty1.md

Add ddusty1.md

---

src/contributors/fa24/eccortes4.md

Add eccortes4 markdown

---

src/contributors/fa24/olasores.md

added olasores info

---

src/contributors/fa24/peterchau.md

add Peter Markdown

---

src/contributors/fa24/avyaktrout.md

Add avyaktrout

---

src/contributors/fa24/quentin_rivest.md

I added my markdown file thingy (called 'quentin_rivest.md')! :)

Baby's First Contrib (QuentinRivest)

---

src/contributors/fa24/daivik.md

Added daivik.md

---

src/contributors/fa24/bryanpham.md

Finished my intro.

---

src/contributors/fa24/thecodeofdaniel.md

I forgot to add "https://" in my link :(

Fix internal link

---

src/contributors/fa24/noah-hw-kim.md

Updated index.html with my name and GitHub account!

Added noah-hw-kim.md

---

src/contributors/sp25/gaballa.md

Add gaballa contributor

---

src/contributors/sp25/jovannadelatrinidad.md

add jovanna as a contributor

---

src/contributors/sp25/JoshuaD.md

Add joshua contributor

---

src/contributors/sp25/timothyouu.md

PLS ADD ME PLS PLS PLS PLS PLS PLS PLS PLS PLS

add timothy ou contributor

---

src/contributors/sp25/ethanthatonekid.md

Add Ethan Davidson as a contributor

---

src/contributors/sp25/jacob-c.md

Add Jacob C as a contributor

---

src/contributors/sp25/Kevingc.md

Added Kevingc as a contributor

---

src/contributors/sp25/hoopla.md

add erik contributor

---

src/contributors/sp25/eldwinn.md

hey it's eldwin

---

src/pages/sp25.astro

I modified the h1 styling in the ```pages/sp25.astro``` file by making a linear gradient with 60 degrees from ```rgb(var(--color-oss-team))``` to ```rgb(17, 150, 212)```. With the modifications, the title changes from all-white to a gradient green/blue color.

Fix Issue #92

---

src/pages/sp25.astro

I corrected the misspellings of "every one" and "initiative" in the paragraph under the header Spring 2025 Contributors.

Fixed Minor Typos in sp25.astro

---

src/components/Scene.svelte

Fix: Contributor Text is closer to the sphere they belong to and will now face the camera for easier reading.

Fixed text positioning and Orientation.

---

src/contributors/sp25/MarkRyanGarcia.md

please approve pls pls pls pls pls

Added MarkRyanGarcia.md

---

src/pages/sp24.astro

Open source software team on top!!

Changed algo to open source software.

---

src/contributors/sp25/tylermlui.md

added tylerlui.md

---

src/contributors/fa25/timothyouu.md

PLS PLS PLS ACCEPT MY PR I AM BEGGING

Added timothyouu.md

---

src/contributors/fa25/AlexthePear.md

Add AlexthePear.md

---

src/contributors/fa25/JacobNguyen.md

ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT ADD IT …

ADDED THE BEST FILE YESSSSS 100% (   secret keylogger :D   )

---

src/contributors/fa25/adamAKH01.md

my name is adam
I need yalls music recommendation

HIIIIIIIIIIIII

---

src/contributors/fa25/chunkys0up.md

Added chunkys0up.md

---

src/contributors/fa25/SamuelValls.md

Added SamuelValls.md
